# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPfw < Formula
  desc "A kubectl plugin for port-forwarding multiple services or pods at once"
  homepage "https://github.com/roeyazroel/kubectl-pfw"
  version "0.0.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.9/kubectl-pfw_0.0.9_darwin_amd64.tar.gz"
      sha256 "b3b7f4804a6249b31db399b1d8bc34643171d76ea7d223127234641100176418"

      def install
        bin.install "kubectl-pfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.9/kubectl-pfw_0.0.9_darwin_arm64.tar.gz"
      sha256 "ffbe28c99fc8a47024f68293bb9f408763d1a386b08ee07cb64cd1324e5040fb"

      def install
        bin.install "kubectl-pfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.9/kubectl-pfw_0.0.9_linux_amd64.tar.gz"
        sha256 "deaa5b528c9e662efb14dffc268ad84b55be39bcd8dfa473d79e3a3012118aa0"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.9/kubectl-pfw_0.0.9_linux_arm64.tar.gz"
        sha256 "0d9a33136562547bb2f03e93e6a6ff2b8c05b33423202d455d8659405420b052"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-pfw --version"
  end
end
