# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPfw < Formula
  desc "A kubectl plugin for port-forwarding multiple services or pods at once"
  homepage "https://github.com/roeyazroel/kubectl-pfw"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.8/kubectl-pfw_0.0.8_darwin_amd64.tar.gz"
      sha256 "876eeca33fad864eac52a53e27d1e12a6b41aeb2b6a81aa4f460a0939340892f"

      def install
        bin.install "kubectl-pfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.8/kubectl-pfw_0.0.8_darwin_arm64.tar.gz"
      sha256 "0334097679fb36af0f2a6399ea2385b9c511f8ffa2dc11fd8ed3877634b292db"

      def install
        bin.install "kubectl-pfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.8/kubectl-pfw_0.0.8_linux_amd64.tar.gz"
        sha256 "595f105318bd2186e25bb1813d964f71de6f6057577273d3a9e680f33d91bca7"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.8/kubectl-pfw_0.0.8_linux_arm64.tar.gz"
        sha256 "a9a2ec2392b384156e46c41fc39b8705b04eff03879f1482165fe08b3c819620"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-pfw --version"
  end
end
