# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPfw < Formula
  desc "A kubectl plugin for port-forwarding multiple services or pods at once"
  homepage "https://github.com/roeyazroel/kubectl-pfw"
  version "0.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.10/kubectl-pfw_0.0.10_darwin_amd64.tar.gz"
      sha256 "8f4707a6701fbac43e409a0554d5e1192683668295e5bf8fe0207517f45d3433"

      def install
        bin.install "kubectl-pfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.10/kubectl-pfw_0.0.10_darwin_arm64.tar.gz"
      sha256 "1a705b18f710ef10cbf7245e7ee992ced2ecb1c02b64ba7b2393af4cb71b8c46"

      def install
        bin.install "kubectl-pfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.10/kubectl-pfw_0.0.10_linux_amd64.tar.gz"
        sha256 "2bc8ca893913b4aa1d925589d0d43207a001116431a57093bf02580c264952f4"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.10/kubectl-pfw_0.0.10_linux_arm64.tar.gz"
        sha256 "fbc9de2e704cd95c3e32cb2a5e283f37d9f19cb16012198384c12939fd1d8c68"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-pfw --version"
  end
end
