# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlPfw < Formula
  desc "A kubectl plugin for port-forwarding multiple services or pods at once"
  homepage "https://github.com/roeyazroel/kubectl-pfw"
  version "0.0.2-SNAPSHOT-5b14520"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.2/kubectl-pfw_0.0.2-SNAPSHOT-5b14520_darwin_amd64.tar.gz"
      sha256 "640794e62a5d29b4ba231e52c0f499bb5a5679003481c8de8162b637cfa46113"

      def install
        bin.install "kubectl-pfw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.2/kubectl-pfw_0.0.2-SNAPSHOT-5b14520_darwin_arm64.tar.gz"
      sha256 "8bc7ff9e22a3bb372308c1d0e58ae840b3414496864c1ed845006518006e2940"

      def install
        bin.install "kubectl-pfw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.2/kubectl-pfw_0.0.2-SNAPSHOT-5b14520_linux_amd64.tar.gz"
        sha256 "cf0752c91b15b424ac7ac08807a2f63d399f8b530f591226b8582909b7ad1b50"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roeyazroel/kubectl-pfw/releases/download/v0.0.2/kubectl-pfw_0.0.2-SNAPSHOT-5b14520_linux_arm64.tar.gz"
        sha256 "bc81a75ce4f3f24a9a2fe98991210937924f81bd274a29283b0996707c819d3f"

        def install
          bin.install "kubectl-pfw"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-pfw --version"
  end
end
